--- Lineweight data tables

CREATE TABLE LINEWEIGHT_DATA (
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DETECTOR INT NOT NULL REFERENCES DETECTOR(ID),    --- the instrument/detector on which the spectrum was collected
    ELEMENT INT NOT NULL,           --- What element is this data for
    COLLECTED TIMESTAMP NOT NULL,   --- When was this data collected
    STANDARD VARCHAR(1024) NOT NULL REFERENCES STANDARD(NAME),
    SPECTRUM INT NOT NULL REFERENCES SPECTRUM(ID),
    FIT_SPECTRUM INT NOT NULL REFERENCES SPECTRUM(ID),
    FANO REAL NOT NULL,
    NOISE REAL NOT NULL,
    SC0 REAL NOT NULL,
    SC1 REAL NOT NULL,
    SC2 REAL DEFAULT 0.0,
    SC3 REAL DEFAULT 0.0,
    SC4 REAL DEFAULT 0.0,
    SC5 REAL DEFAULT 0.0,
    BEAM_ENERGY REAL NOT NULL,
    PROBE_DOSE REAL NOT NULL
);

CREATE INDEX ELEMENT_INDEX ON LINEWEIGHT_DATA(DETECTOR, ELEMENT);

CREATE TABLE LINE_DATUM (
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LWDID INT NOT NULL REFERENCES LINEWEIGHT_DATA(ID),
    INNER_SH INT NOT NULL,
    OUTER_SH INT NOT NULL,
    INTENISITY REAL NOT NULL,
    DINTENSITY REAL NOT NULL
);

CREATE UNIQUE INDEX LINE_DATUM_INDEX ON LINE_DATUM(SETID,LINE);
